#include "main.h"

namespace auton {

float MAX_SPEED = 67;
float MAX_ACCEL = 130;
#define A Angle
#define V Vector

void rush_6b() {
  Trajectory2D::set_constraints(70, 130, 15, 11.0);
  Trajectory1D::set_constraints(70, 140, 15);
  sys_task::intake_req = 1;
  sys_task::front_wings_req = 1;
  pros::delay(200);
  sys_task::front_wings_req = 0;
  robot.follow_prim(CubicBezier(V(-19, 44), V(-19, 44), 15.0), 1);
  robot.move(0);
  pros::delay(100);
  robot.follow_prim(CubicBezier(V(-33, 52), V(-33, 52), 12.0), -2);
  sys_task::intake_req = 0;
  robot.stop_fast();
  robot.turn_pt(A(45, Unit::DEGREES));
  robot.move(0);
  sys_task::intake_rev_req = 1;
  pros::delay(200);
  robot.turn_pt(A(-90, Unit::DEGREES));
  sys_task::intake_rev_req = 0;
  sys_task::intake_req = 1;
  robot.move(0);
  robot.straight(38);
  robot.stop_fast();
  pros::delay(100);
  Trajectory2D::set_constraints(51, 96, 15, 11.0);
  robot.follow_prim(
      []() {
        pros::delay(200);
        sys_task::intake_req = 0;
        pros::delay(550);
        sys_task::left_wing_req = 1;
        sys_task::right_wing_req = 1;
        pros::delay(500);
        // sys_task::left_wing_req = 0;
      },
      CubicBezier(V(-17,50), V(-17, 50), 57.0), -1);
  // robot.straight(-3);

  // robot.straight(-30);
  // robot.move(0);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  // robot.turn_pt(Angle(-135, Unit::DEGREES));
  // robot.stop();
  // sys_task::left_wing_req = 1;
  // sys_task::right_wing_req = 1;
  // sys_task::intake_req = 0;
  // robot.straight(-21);
  // robot.stop_fast();
  // robot.turn_pt(Angle(-135, Unit::DEGREES));
  // robot.stop_fast();
  // sys_task::left_wing_req = 0;
  // pros::delay(150);
  robot.move(0);
  // robot.straight(14);
  // robot.stop_fast();
  // robot.follow_prim(CubicBezier(V(0, 18), V(-14, 30), 6.0), -1);
  // robot.stop_fast();
  sys_task::right_wing_req = 0;
  sys_task::left_wing_req = 0;
  robot.turn_pt(A(-160, Unit::DEGREES));
  robot.move(-127);
  pros::delay(500);
  robot.stop_fast();
  // robot.turn_pt(Angle(-175, Unit::DEGREES));
  // robot.stop_fast();
  // sys_task::right_wing_req = 1;

  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 60);
  sys_task::right_wing_req = 0;
  // robot.straight(-35);
  // robot.stop_fast();

  sys_task::left_wing_req = 0;
  robot.move(0);
  // robot.turn_swing(A(180, Unit::DEGREES), 1);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  // robot.straight(-15);
  // robot.stop_fast();
  sys_task::right_wing_req = 0;
  robot.straight(11);
  robot.stop_fast();
  robot.turn_pt(A(15, Unit::DEGREES));
  sys_task::intake_rev_req = 1;
  pros::delay(250);
  robot.straight(31);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.stop_fast();
  pros::delay(200);
  robot.straight(-8);

  sys_task::intake_rev_req = 0;
  robot.turn_pt(A(-62, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 1;
  Trajectory1D::set_constraints(70, 160, 30);
  robot.straight(63);
  robot.straight(-6);
  robot.stop_fast();
  robot.turn_pt(A(67, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 0;
  sys_task::intake_speed = 127;
  sys_task::intake_rev_req = 1;
  robot.straight(10);
  sys_task::intake_rev_req = 0;
  sys_task::intake_speed = 127;
  sys_task::intake_req = 1;
  robot.turn_pt(A(-40, Unit::DEGREES));
  robot.straight(45);
  robot.stop_fast();
  robot.straight(-3);
  robot.turn_pt(A(90, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 0;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 70);
  sys_task::front_wings_req = 1;
  sys_task::intake_rev_req = 1;
  pros::delay(200);
  robot.straight(55);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  sys_task::front_wings_req = 0;
  sys_task::intake_rev_req = 0;
  pros::delay(150);
  robot.straight(-10);
  robot.stop();
}

void safe_6b() {
  sys_task::intake_req = 1;
  pros::delay(250);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  robot.straight(12);
  robot.stop_fast();
  Trajectory2D::set_constraints(50, 95, 15, 11.0);
  Trajectory2D::set_constraints(51, 96, 15, 11.0);
  robot.follow_prim(
      []() {
        pros::delay(200);
        sys_task::intake_req = 0;
        pros::delay(550);
        sys_task::left_wing_req = 1;
        sys_task::right_wing_req = 1;
        pros::delay(500);
        // sys_task::left_wing_req = 0;
      },
      CubicBezier(V(-17,50), V(-17, 50), 57.0), -1);
  // robot.straight(-3);

  // robot.straight(-30);
  // robot.move(0);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  // robot.turn_pt(Angle(-135, Unit::DEGREES));
  // robot.stop();
  // sys_task::left_wing_req = 1;
  // sys_task::right_wing_req = 1;
  // sys_task::intake_req = 0;
  // robot.straight(-21);
  // robot.stop_fast();
  // robot.turn_pt(Angle(-135, Unit::DEGREES));
  // robot.stop_fast();
  // sys_task::left_wing_req = 0;
  // pros::delay(150);
  robot.move(0);
  // robot.straight(14);
  // robot.stop_fast();
  // robot.follow_prim(CubicBezier(V(0, 18), V(-14, 30), 6.0), -1);
  // robot.stop_fast();
  sys_task::right_wing_req = 0;
  sys_task::left_wing_req = 0;
  robot.turn_pt(A(-65, Unit::DEGREES));
  robot.move(-127);
  pros::delay(700);
  robot.stop_fast();
  // robot.turn_pt(Angle(-175, Unit::DEGREES));
  // robot.stop_fast();
  // sys_task::right_wing_req = 1;

  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 60);
  sys_task::right_wing_req = 0;
  // robot.straight(-35);
  // robot.stop_fast();

  sys_task::left_wing_req = 0;
  robot.move(0);
  // robot.turn_swing(A(180, Unit::DEGREES), 1);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  // robot.straight(-15);
  // robot.stop_fast();
  sys_task::right_wing_req = 0;
  robot.straight(11);
  robot.stop_fast();
  robot.turn_pt(A(112, Unit::DEGREES));
  sys_task::intake_rev_req = 1;
  pros::delay(250);
  robot.straight(31);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.stop_fast();
  pros::delay(200);
  robot.straight(-8);

  sys_task::intake_rev_req = 0;
  robot.turn_pt(A(28, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 1;
  Trajectory1D::set_constraints(70, 140, 15);
  robot.straight(63);
  robot.straight(-6);
  robot.stop_fast();
  robot.turn_pt(A(90+66, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 0;
  sys_task::intake_speed = 60;
  sys_task::intake_rev_req = 1;
  robot.straight(14);
  sys_task::intake_rev_req = 0;
  sys_task::intake_speed = 127;
  sys_task::intake_req = 1;
  robot.turn_pt(A(43, Unit::DEGREES));
  robot.straight(46);
  robot.stop_fast();
  robot.straight(-9);
  robot.turn_pt(A(175, Unit::DEGREES));
  robot.stop_fast();
  sys_task::intake_req = 0;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 70);
  sys_task::front_wings_req = 1;
  sys_task::intake_rev_req = 1;
  pros::delay(200);
  robot.straight(55);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  sys_task::front_wings_req = 0;
  sys_task::intake_rev_req = 0;
  pros::delay(150);
  robot.straight(-10);
  robot.stop();
}

void safe_4b() {
  sys_task::intake_req = 1;
  pros::delay(250);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  robot.straight(12);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED * 0.65, MAX_ACCEL, 5);
  robot.straight(-26);
  robot.stop();
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  robot.turn_pt(A(-45, Unit::DEGREES));
  // robot.stop();
  sys_task::left_wing_req = 1;
  sys_task::right_wing_req = 1;
  sys_task::intake_req = 0;
  robot.straight(-16);
  sys_task::left_wing_req = 0;
  pros::delay(150);
  robot.stop();
  robot.turn_pt(A(-85, Unit::DEGREES));
  // robot.stop();
  // sys_task::right_wing_req = 1;

  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  sys_task::right_wing_req = 0;
  robot.straight(-35);
  // robot.stop();
  robot.straight(11);
  robot.straight(-35);
  robot.stop();
  robot.straight(11);
  robot.turn_pt(A(101, Unit::DEGREES));
  sys_task::intake_rev_req = 1;
  pros::delay(250);
  robot.straight(31);
  robot.straight(-20);
  robot.straight(31);
  robot.straight(-27);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  sys_task::intake_rev_req = 0;
  robot.stop();
  sys_task::intake_rev_req = 0;
  robot.turn_pt(A(28, Unit::DEGREES));
  robot.stop();
  sys_task::intake_req = 1;
  robot.straight(57);
  robot.straight(-6);
  robot.stop();
  robot.turn_pt(A(150, Unit::DEGREES));
  robot.stop();
  robot.straight(23);
  robot.turn_pt(A(180, Unit::DEGREES));
  robot.stop();
  sys_task::intake_req = 0;
  sys_task::intake_rev_req = 1;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  robot.straight(35);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.straight(-5);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  robot.straight(20);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.straight(-5);
  robot.stop();
  sys_task::intake_rev_req = 0;
  pros::delay(2);
}

void safe_3b_touch() {
  sys_task::intake_req = 1;
  pros::delay(250);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  robot.straight(12);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED * 0.65, MAX_ACCEL, 5);
  robot.straight(-26);
  robot.stop();
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  robot.turn_pt(A(-45, Unit::DEGREES));
  // robot.stop();
  sys_task::left_wing_req = 1;
  sys_task::right_wing_req = 1;
  sys_task::intake_req = 0;
  robot.straight(-16);
  sys_task::left_wing_req = 0;
  pros::delay(150);
  robot.stop();
  robot.turn_pt(A(-85, Unit::DEGREES));
  // robot.stop();
  // sys_task::right_wing_req = 1;

  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  sys_task::right_wing_req = 0;
  robot.straight(-35);
  // robot.stop();
  robot.straight(11);
  robot.straight(-35);
  robot.stop();
  robot.straight(11);
  robot.turn_pt(A(101, Unit::DEGREES));
  sys_task::intake_rev_req = 1;
  pros::delay(250);
  robot.straight(31);
  robot.straight(-11);
  robot.straight(31);
  robot.straight(-13);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  sys_task::intake_rev_req = 0;
  robot.stop();
  robot.turn_pt(A(-45, Unit::DEGREES));
  robot.stop();
  robot.straight(40);
  robot.stop();
  robot.turn_pt(A(0, Unit::DEGREES));
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED * 0.55, MAX_ACCEL, 5);
  robot.straight(28.8);
  robot.stop();
}

void safe_close() {
  sys_task::intake_req = 1;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.turn_pt(A(45, Unit::DEGREES));
  robot.straight(-20);
  robot.turn_pt(A(90, Unit::DEGREES));
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  robot.straight(-25);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.stop();
  robot.straight(11);
  sys_task::intake_req = 0;
  robot.turn_pt(A(-135, Unit::DEGREES));
  sys_task::left_wing_req = 1;
  robot.stop();
  robot.straight(-16);
  sys_task::left_wing_req = 0;
  robot.turn_pt(A(175, Unit::DEGREES));
  robot.turn_pt(A(-175, Unit::DEGREES));
  // robot.straight(2);
  robot.turn_pt(A(2, Unit::DEGREES));
  robot.stop();
  sys_task::intake_rev_req = 1;
  Trajectory1D::set_constraints(MAX_SPEED * 0.55, MAX_ACCEL, 5);
  robot.straight(34.5);
  robot.stop();
  pros::delay(500);
  sys_task::intake_rev_req = 0;
  pros::delay(100);
}

void rush_close() {
  sys_task::intake_req = 1;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 15);
  sys_task::front_wings_req = 1;
  robot.turn_pt(A(19.6, Unit::DEGREES));
  sys_task::front_wings_req = 0;
  robot.stop();
  robot.straight(54.8);
  robot.stop();
  pros::delay(300);
  robot.straight(-45.2);
  robot.stop();
  robot.turn_pt(A(90, Unit::DEGREES));
  robot.stop();
  sys_task::intake_req = 0;
  sys_task::intake_rev_req = 1;
  pros::delay(500);
  Trajectory1D::set_constraints(MAX_SPEED * 0.55, MAX_ACCEL, 5);
  robot.straight(29);
  sys_task::intake_rev_req = 0;
  robot.stop();
  pros::delay(100);
  // robot.turn_pt(A(135, Unit::DEGREES));
  // robot.straight(-24.5);
  // robot.turn_pt(A(180, Unit::DEGREES));
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  // robot.straight(-25);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(12.4);
  // sys_task::intake_rev_req = 0;
  // robot.turn_pt(A(-43, Unit::DEGREES));
  // sys_task::left_wing_req = 1;
  // robot.stop();
  // robot.straight(-16.4);
  // sys_task::left_wing_req = 0;
  // robot.turn_pt(A(-85, Unit::DEGREES));
  // robot.turn_pt(A(-95, Unit::DEGREES));
  // robot.stop();
  // robot.turn_pt(A(93, Unit::DEGREES));
  // robot.stop();
  // sys_task::intake_rev_req = 1;
  // Trajectory1D::set_constraints(MAX_SPEED * 0.55, MAX_ACCEL, 5);
  // robot.straight(34.5);
  // robot.stop();
  // pros::delay(500);
  // sys_task::intake_rev_req = 0;
  // pros::delay(100);
}

void skills() {
  Trajectory2D::set_constraints(67, 100, 15, 11.0);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.follow_prim(CubicBezier(V(0, 18), V(-14, 30), 6.0), -1);
  robot.move(-127);
  pros::delay(400);
  robot.follow_prim(CubicBezier(V(-8, 16), V(-8, 16), 13.0), 2);
  robot.turn_pt(A(21 + 45, Unit::DEGREES));
  sys_task::cata_req = 1;
  robot.straight(-8);
  sys_task::left_wing_req = 1;
  robot.turn_pt(A(21 + 45, Unit::DEGREES));
  robot.stop();
  robot.turn_pt(A(21 + 45, Unit::DEGREES));
  robot.stop();
  // pros::delay(23500);
  pros::delay(22000 * 1);
  // pros::delay(300);
  sys_task::cata_req = 0;
  pros::delay(2);

  sys_task::left_wing_req = 0;

  robot.straight(17);
  sys_task::front_wings_req = 1;
  robot.follow_prim(CubicBezier(V(80, 70), V(80, 70), 60.0), 1);
  robot.stop();
  sys_task::front_wings_req = 0;
  robot.straight(-2);
  robot.stop();
  robot.turn_pt(A(36, Unit::DEGREES));
  robot.stop();
  robot.straight(-45);
  robot.stop();
  robot.turn_pt(A(90, Unit::DEGREES));
  robot.stop();
  sys_task::front_wings_req = 1;
  // pros::delay(100);
  robot.straight(42);
  robot.stop();
  sys_task::front_wings_req = 0;
  robot.straight(10);
  robot.stop();
  robot.turn_pt(A(44, Unit::DEGREES));
  robot.stop();
  pros::delay(250);

  Trajectory2D::set_constraints(55, 100, 15, 11.0);
  robot.follow_prim(CubicBezier(V(5, 90), V(-33, 90), 55), 1);
  robot.move(80);
  pros::delay(200);
  robot.stop();
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 40);
  robot.straight(-21.5);
  robot.stop();
  // robot.turn_pt(A(-40, Unit::DEGREES));
  // robot.move(90);
  // pros::delay(400);
  // robot.stop();
  // robot.straight(-6);
  robot.stop();
  robot.turn_pt(A(69, Unit::DEGREES));
  robot.straight(-56);
  robot.stop();

  robot.turn_pt(A(19, Unit::DEGREES));
  sys_task::front_wings_req = 1;
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 40);
  robot.straight(70);
  robot.stop();
  sys_task::front_wings_req = 0;
  pros::delay(400);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.straight(-30);
  sys_task::wings_req = 1;
  robot.stop();
  robot.turn_pt(A(135, Unit::DEGREES));
  robot.straight(-30);
  robot.stop();
  robot.turn_pt(A(-115, Unit::DEGREES));
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 40);
  robot.straight(-63);
  robot.stop();
  Trajectory2D::set_constraints(67, 100, 15, 11.0);
  robot.straight(30);
  sys_task::wings_req = 0;
  // robot.straight(25);
  robot.stop();
  robot.turn_pt(A(-11, Unit::DEGREES));
  sys_task::front_wings_req = 1;
  robot.straight(65);
  robot.stop();
  robot.turn_pt(A(100, Unit::DEGREES));
  robot.stop();
  robot.straight(55);
  robot.stop();
  sys_task::front_wings_req = 0;
  robot.straight(-10);
  robot.straight(30);
  robot.stop();
  robot.straight(-10);
  robot.straight(30);
  robot.stop();
  robot.straight(-18);
  robot.stop();
  // sys_task::intake_req = 1;
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // // robot.set_heading(A(-45, Unit::DEGREES));
  // robot.straight(-22.5);
  // robot.turn_pt(A(-30, Unit::DEGREES));
  // // robot.stop();
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  // robot.straight(-37);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(21);
  // robot.stop();
  // robot.turn_pt(A(20+45, Unit::DEGREES));
  // sys_task::intake_req = 0;
  // sys_task::cata_req = 1;
  // robot.straight(-8);
  // sys_task::left_wing_req = 1;
  // robot.turn_pt(A(20+45, Unit::DEGREES));
  // robot.stop();
  // pros::delay(29000);
  // sys_task::cata_req = 0;
  // pros::delay(2);

  // sys_task::left_wing_req = 0;
  // robot.straight(29);
  // robot.stop();
  // robot.turn_pt(A(60+45, Unit::DEGREES));
  // robot.stop();
  // sys_task::intake_rev_req = 1;
  // robot.straight(38);
  // robot.stop();
  // robot.turn_pt(A(45, Unit::DEGREES));
  // robot.stop();
  // robot.straight(-7);
  // robot.stop();
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL+30, 60);
  // sys_task::front_wings_req = 1;
  // // robot.straight(180);
  // robot.turn_pt(A(45, Unit::DEGREES));
  // robot.stop();
  // robot.move(127);
  // pros::delay(2500);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(-15);
  // robot.turn_pt(A(50, Unit::DEGREES));
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL+30, 60);
  // robot.straight(50);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(-25);
  // robot.turn_pt(A(40, Unit::DEGREES));
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL+30, 60);
  // robot.straight(50);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(-25);
  // robot.turn_pt(A(45, Unit::DEGREES));
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL+30, 60);
  // robot.straight(50);
}

void skills_start() {

  Trajectory2D::set_constraints(67, 100, 15, 11.0);
  Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  robot.follow_prim(CubicBezier(V(0, 18), V(-14, 30), 6.0), -1);
  robot.move(-127);
  pros::delay(400);
  robot.follow_prim(CubicBezier(V(-8, 16), V(-8, 16), 13.0), 2);
  robot.turn_pt(A(21 + 45, Unit::DEGREES));
  sys_task::cata_req = 1;
  robot.straight(-8);
  sys_task::left_wing_req = 1;
  robot.turn_pt(A(21.5 + 45, Unit::DEGREES));
  robot.stop();
  robot.turn_pt(A(21.5 + 45, Unit::DEGREES));
  robot.stop();
  pros::delay(22000 * 1);
  // pros::delay(60000);
  // pros::delay(500);
  sys_task::cata_req = 0;
  pros::delay(2);

  sys_task::left_wing_req = 0;

  // sys_task::intake_req = 1;
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // // robot.set_heading(A(-45, Unit::DEGREES));
  // robot.straight(-22.5);
  // robot.turn_pt(A(-30, Unit::DEGREES));
  // // robot.stop();
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 50);
  // robot.straight(-37);
  // Trajectory1D::set_constraints(MAX_SPEED, MAX_ACCEL, 10);
  // robot.straight(21);
  // robot.stop();
  // robot.turn_pt(A(20 + 45, Unit::DEGREES));
  // sys_task::intake_req = 0;
  // sys_task::cata_req = 1;
  // robot.straight(-8);
  // sys_task::left_wing_req = 1;
  // robot.turn_pt(A(20 + 45, Unit::DEGREES));
  // robot.stop();
  // pros::delay(29000);
  // sys_task::cata_req = 0;
  // pros::delay(2);
}

} // namespace auton